CREATE TABLE trades
(
  id SERIAL,
  parent_trade_id INT NULL,
  from_account_id INT NULL,
  to_account_id INT NULL,
  asset_id INT NOT NULL,
  source_id INT NOT NULL,
  uuid uuid NOT NULL DEFAULT uuid_generate_v4(),
  transaction_id VARCHAR(4000) NOT NULL,
  order_id VARCHAR(255) NULL,
  trade_id VARCHAR(255) NULL,
  name VARCHAR(255) NOT NULL,
  alternate_name VARCHAR(255) NULL,
  trade_type_id INT NULL,
  trade_date timestamp NOT NULL,
  settle_date timestamp NULL,
  transfer_date timestamp NULL,
  from_quantity NUMERIC NULL,
  to_quantity NUMERIC NULL,
  price NUMERIC NULL,
  total_amount NUMERIC NULL,
  fees_amount NUMERIC NULL,
  fees_asset_id INT NULL,
  realized_return_amount NUMERIC NULL,
  realized_return_asset_id INT NULL,
  cost_basis_amount NUMERIC NULL,
  cost_basis_trade_id INT NULL,
  description TEXT NULL,
  is_active BOOLEAN NOT NULL,
  source_data jsonb NULL,
  created_by VARCHAR(255) NOT NULL,
  created_at timestamp NOT NULL,
  updated_by VARCHAR(255) NOT NULL,
  updated_at timestamp NOT NULL,
  PRIMARY KEY(id),
  CONSTRAINT fk_parent_trade FOREIGN KEY(parent_trade_id) REFERENCES trades(id),
  CONSTRAINT fk_from_account FOREIGN KEY(from_account_id) REFERENCES accounts(id),
  CONSTRAINT fk_from_to_account FOREIGN KEY(to_account_id) REFERENCES accounts(id),
  CONSTRAINT fk_asset FOREIGN KEY(asset_id) REFERENCES assets(id),
  CONSTRAINT fk_trade_type FOREIGN KEY(trade_type_id) REFERENCES structured_values(id),
  CONSTRAINT fk_fees_asset FOREIGN KEY(fees_asset_id) REFERENCES assets(id),
  CONSTRAINT fk_realized_return_asset FOREIGN KEY(realized_return_asset_id) REFERENCES assets(id),
  CONSTRAINT fk_cost_basis_trade FOREIGN KEY(cost_basis_trade_id) REFERENCES trades(id)
);
